path:
  ckpt_path: "/tmp/zhangyuqiang/master_dataset_models/fs2_mfa_phone_emo/model/output/ckpt/emo_multispeaker"
  log_path: "/tmp/zhangyuqiang/master_dataset_models/fs2_mfa_phone_emo/model/output/log/emo_multispeaker"
  result_path: "/tmp/zhangyuqiang/master_dataset_models/fs2_mfa_phone_emo/model/output/result/emo_multispeaker"
  pretrained_checkpoint_path: "/tmp/zhangyuqiang/master_dataset_models/fs2_mfa_phone_emo/model/350000.pth.tar"

optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 100
  anneal_steps: [120000, 150000, 180000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 1000
  synth_step: 5000
  val_step: 1000
  save_step: 10000


